---
# Source: k8s-config/templates/config.yaml
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.31.2
clusterName: dummy-cluster
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
controlPlaneEndpoint: 192.168.180.143:9000
networking:
  podSubnet: 10.100.0.0/16
  serviceSubnet: 10.120.0.0/16
apiServer:
  certSANs:
    - 192.168.180.143
    - 10.10.0.162
  extraArgs:
    - name: max-requests-inflight
      value: "1000"
    - name: max-mutating-requests-inflight
      value: "500"
etcd:
  external:
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
    endpoints:
      - https://10.10.0.161:2379
---
# Source: k8s-config/templates/init.yaml
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
localAPIEndpoint:
  advertiseAddress: 10.10.0.162
