
{{- if .Values.generate.clusterConfig }}
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: {{ .Values.clusterConfig.version }}
clusterName: {{ .Values.clusterConfig.name }}
controlPlaneEndpoint: {{ .Values.clusterConfig.controlPlaneAPIEndpoint }}
{{- with .Values.clusterConfig.networking }}
networking:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.clusterConfig.apiServer }}
apiServer:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.clusterConfig.etcd }}
etcd:
  {{- toYaml . | nindent 2 }}
{{- end}}    
{{- end }}
