{{- if .Values.generate.clusterJoin }}
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
discovery:
  bootstrapToken:
    apiServerEndpoint: {{ .Values.clusterConfig.advertiseAddress }}
    token: {{ .Values.clusterInit.defaultKubeADMToken }}
{{- if .Values.clusterJoin.joinControlPlane }}
controlPlane:
  localAPIEndpoint:
  advertiseAddress: {{ .Values.clusterConfig.advertiseAddress }}
{{- if hasKey .Values.clusterConfig "bindPort" }}
  bindPort: {{ .Values.clusterConfig.bindPort }}
{{- end }}
{{- end }}
{{- end }}
