{{- if .Values.generate.etcdKubelet }}
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
cgroupDriver: systemd
address: 127.0.0.1
containerRuntimeEndpoint: {{ .Values.etcdKubelet.containerRuntimeEndpoint }}
staticPodPath: /etc/kubernetes/manifests
{{- end }}
