
{{- if .Values.generate.etcdCluster }}
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
etcd:
  local:
    serverCertSANs:
    - {{ .Values.etcdCluster.advertiseAddress }}
    peerCertSANs:
    - {{ .Values.etcdCluster.advertiseAddress }}
    extraArgs:
      - name: initial-cluster
        value: {{ .Values.etcdCluster.initialCluster }}
      - name: initial-cluster-state
        value: new
      - name: listen-peer-urls
        value: https://{{ .Values.etcdCluster.advertiseAddress }}:2380
      - name: listen-client-urls
        value: https://{{ .Values.etcdCluster.advertiseAddress }}:2379
      - name: advertise-client-urls
        value: https://{{ .Values.etcdCluster.advertiseAddress }}:2379
      - name: initial-advertise-peer-urls
        value: https://{{ .Values.etcdCluster.advertiseAddress }}:2380
{{- end }}
