{{- if .Values.join.enabled }}
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
discovery:
  bootstrapToken:
    apiServerEndpoint: {{ .Values.config.advertiseAddress }}
    token: {{ .Values.init.defaultKubeADMToken }}
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: KubeletConfiguration
{{- end }}
