{{- if .Values.join.enabled }}
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
discovery:
  bootstrapToken:
    apiServerEndpoint: {{ .Values.config.advertiseAddress }}
    token: {{ .Values.init.defaultKubeADMToken }}
{{- if .Values.join.joinControlPlane }}
controlPlane:
  localAPIEndpoint:
  advertiseAddress: {{ .Values.config.advertiseAddress }}
{{- if hasKey .Values.config "bindPort" }}
  bindPort: {{ .Values.config.bindPort }}
{{- end }}
{{- end }}
{{- end }}
